apiVersion: v1
kind: Pod 
metadata:
  name: selective-pod 
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh","-c"]
      args:
        - echo " color=$Color"; echo "Port=$PORT"; sleep 3600
      env:
        - name: Color
          valueFrom: 
            configMapKeyRef:
              name: cm-1
              key: APP_COLOR
        - name: PORT
          valueFrom: 
            configMapKeyRef:
              name: cm-1
              key: APP_PORT